class_name DefenseRuntime
extends RefCounted

var mercenaryAssignmentManager: DefenseMercenaryAssignmentManager

var towerManager: DefenseTowerManager
var machineManager: DefenseMachineManager
var trapManager: DefenseTrapManager
var monsterManager: DefenseMonsterManager

var cpManager: DefenseCPManager
var spawnManager: DefenseSpawnManager
var timeManager: DefenseTimeManager
var targetingManager: DefenseTargetingManager
var combatManager: DefenseCombatManager

var unitLifecycle: DefenseUnitLifecycle
var mercenaryBuffService: DefenseMercenaryBuffService
var characterRemovalService: DefenseCharacterRemovalService

var deploymentController: DefenseDeploymentController
var installableDeploymentController: DefenseInstallableDeploymentController
var spawnController: DefenseSpawnController
